[package]
name = "onnx-optimizer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.18.0"
onnx-proto = { path = "onnx-proto" }
petgraph = "0.8.2"
prost = "0.13"
strum = "0.27.2"
strum_macros = "0.27.2"
sysinfo = "0.37.0"
thiserror = "2.0.12"

[dev-dependencies]
hf-hub = "0.4.3"
ort = "1.16.3"
tempfile = "3.8"
